GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e65430bc5ea0b13bc92e7ad

###

POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Person",
    "subscribedToChannel": "Web Dev Simplified"
}   

###

DELETE http://localhost:3000/subscribers/5e65430dc5ea0b13bc92e7ae

### 

PATCH http://localhost:3000/subscribers/5e65496a8693143fbc5ddd3e
Content-Type: application/json

{
    "name": "New Name"
}



